config/routes.rb
# Defines the app's routes
# @author Chris Loftus
Rails.application.routes.draw do
  resources :posts do
    resources :replies, except: [:index, :show, :edit, :update, :destroy]
  end
  resources :users do
    # We add a special route to support the search field
    get 'search', on: :collection
  end
  
  # At the moment we only provide a JSON web service
  # API for user account managment. This is provided
  # as an example. See the rest_client folder.
  namespace :api, defaults: {format: :json} do
    resources :users, except: [:new, :edit] do
      get 'search', on: :collection
    end
    resources :posts, except: [:new, :edit]
    resource :session, only: [:create]

  end

  # No point allowing the editing or update of an existing broadcast
  resources :broadcasts, except: [:edit, :update]

  # A singleton resource and so no paths requiring ids are generated
  # Also, don't want to support editing of the session
  resource :session, only: [:new, :create, :destroy]

  # This is just to support the landing page
  get 'home', to: 'home#index', as: :home

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/notifications/_notification.html.erb
<div class="notification">
  <div class="left">
    <%= image_for(notification.user, :small, true) %>
  </div>
  <div class="right">
    <div class="user">
      <a href="<%= user_path(notification.user.id) %>">
        <%= notification.user.firstname %> <%= notification.user.surname %>
      </a>
    </div>
    <div class="timestamp">
      <a href="<%= broadcast_path(notification.id) %>">
        <%= notification.created_at.strftime("%d/%m/%y %H:%M:%S") %>
      </a>
    </div>
    <div class="content"><%= notification.content %></div>
  </div>
  <br style="clear: both"/>
</div>

app/views/notifications/_notifications.html.erb
<!-- Code taken and modified by cwl from Kieran Dunbar's assignment solution 2016-17 -->
<div id="notification_feed">
  <% if @notifications.length > 0 %>
      <% @notifications.each do |notification| %>
          <%= render partial: 'notifications/notification', locals: {notification: notification} %>
      <% end %>
  <% end %>
</div>