config/routes.rb
# Defines the app's routes
# @author Chris Loftus
Rails.application.routes.draw do
  resources :posts do
    resources :replies, except: [:index, :show, :edit, :update, :destroy]
  end
  resources :users do
    # We add a special route to support the search field
    get 'search', on: :collection
  end
  
  # At the moment we only provide a JSON web service
  # API for user account managment. This is provided
  # as an example. See the rest_client folder.
  namespace :api, defaults: {format: :json} do
    resources :users, except: [:new, :edit] do
      get 'search', on: :collection
    end
    resources :posts, except: [:new, :edit]
    resource :session, only: [:create]

  end

  # No point allowing the editing or update of an existing broadcast
  resources :broadcasts, except: [:edit, :update]

  # A singleton resource and so no paths requiring ids are generated
  # Also, don't want to support editing of the session
  resource :session, only: [:new, :create, :destroy]

  # This is just to support the landing page
  get 'home', to: 'home#index', as: :home

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :replies, dependent: :destroy
  validates_presence_of :title, :body
  self.per_page = 8

  validate :text_editor_blank
  
  #adds extra validation so that CKEditor form can't be submitted without actual text  
  def text_editor_blank
    if body == "<p>&nbsp;</p>" 
      errors.add(:body, "can't be blank")
    end
  end

end

app/controllers/api/posts_controller.rb
# Handles incoming user account HTTP JSON web service requests
# @author Chris Loftus
class API::PostsController < API::ApplicationController
  skip_before_action :verify_authenticity_token
	before_action :set_post, only: [:show, :destroy, :update]

  # GET /api/users.json
  def index
    # If the REST client wants everything using the all query
    # parameter, then give it everything!
    if params.key?(:all)
      @posts = Post.all.order('created_at DESC')
    else
      @posts = Post.paginate(page: params[:page],
			   per_page: params[:per_page])
                 .order('created_at DESC')
    end
    
  end

  # GET /api/users/1.json
  def show
    respond_to do |format|
      format.json
    end
  end

  # POST /api/users.json
  def create
    respond_to do |format|
      format.json do
        @post = Post.new(post_params)
	@post.user_id = current_user.id #so the client doesn't need to ask for a user ID

        if @post.save # Will attempt to save user and image
          head :created, location: api_post_url(@post)
        else
          render json: @post.errors, status: :unprocessable_entity
        end
      end
    end
  end

  private
  def post_params
	  params.require(:post).permit(:title, :body, :user_id, :anonymous)
  end

  def set_post
      @post = Post.find(params[:id])
    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :login_required
  before_action :set_current_page, except: [:index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page],
			   per_page: params[:per_page])
                 .order('created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      #checks for recaptcha
      if verify_recaptcha(model: @post) && @post.save
	@userPost = UserPostTime.new
	@userPost.post_id = @post.id
	@userPost.user_id = @post.user_id
	@userPost.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if verify_recaptcha(model: @post) && @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url(page: @current_page)}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :anonymous)
    end

    def set_current_page
      @current_page = params[:page] || 1
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  $replies = Array.new
  $count = 1 
 
  #recursive function to go through each reply and it's own replies and returns them in the appropraite order. 
  def getReplies(post)
    post.replies.each do |reply|
      $count += 1
      $replies.push([reply, $count])
      #recursively calls itself with the child reply
      getReplies(reply)
      $count -= 1
    end
    return $replies 
  end

  #clears the global variables
  def clearVars
    $replies = Array.new
    $count = 1
  end

  #this is called in the posts index for each post
  def checkPosts(post, currentUser)
	  # checks to see whether the user has read the post
    if (!UserPostTime.select(:created_at).where(user_id: currentUser, post_id: post.id).any?)
      return post.replies.count+1   
    else
      unreadPosts = 0
      lastTime = UserPostTime.select(:created_at).where(user_id: currentUser, post_id: post.id).first.created_at
      replyCount = Reply.where(post_id: post.id).where("created_at > ?", lastTime).count
    end
  end

  #this is called when the user reads looks at a post
  def readPost(post, currentUser)
    #adds an extra view to the view counter for the post
    post.views += 1
    post.save

    #looks for an existing time record for the user and post, if one doesn't exist it creates one, if it already exists, it updates the current time to now.
    userPost = UserPostTime.find_or_initialize_by(user_id: currentUser, post_id: post.id)
    userPost.created_at = DateTime.now
    userPost.save!
  end

end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag 'page', @current_page %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="field">          
    <%= hidden_field_tag :user_id, current_user.id %>
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="field">
    <input type="checkbox" name="post[anonymous]" id="anonymous" value="true"> Post as Anonymous<br>

  </div>
  <%= recaptcha_tags %>

  <div class="actions">
    <%= form.submit %>
  </div>
  <script>
      ClassicEditor
          .create( document.querySelector( '#post_body' ) )
          .catch( error => {
              console.error( error );
          } );
  </script>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', post_path(@post, page: @current_page) %> |
<%= link_to 'Back', posts_path(page: @current_page) %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<% if @posts.length > 0 %>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Thread</th>
      <th>Author</th>
      <th>Unread Posts</th>
      <th>Total Posts</th>
      <th>Total Views</th>
      <th>Last Post</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
      <% @posts.each do |post| %>
      <% if post.anonymous %>
	      <% @name = "anonymous" %>
      <% else %>
        <% @name = post.user.firstname + " " + post.user.surname %>
      <% end %>
      <tr class="data">
        <td><%= post.created_at.strftime("%m/%d/%y %H:%M") %></td>
	<td class="title"><%= link_to post.title, post %></td>
	<% if !post.anonymous %>
	  <td class="author"><%= link_to @name, post.user %></td>
        <% else %>
	  <td class="author"><%= @name %></td>
        <% end %>
        <td class="unread"><%= checkPosts(post, current_user.id) %></td>
	<td class="total"><%= post.replies.count+1 %></td>
        <td><%= post.views %></td>
        <% lastPost = post.replies.last %>
	<td>
		<% if(lastPost != nil) %>
			<% if !lastPost.anonymous %>
				<p>By: <%= lastPost.user.firstname + " " + lastPost.user.surname %></p>
			<% else %>
				<p>anonymous</p>
		        <% end %>
                        <strong><%= lastPost.created_at.strftime("%m/%d/%y %H:%M") %></strong>
		<% else %>
			<% if !post.anonymous %>
				<p>By: <%= post.user.firstname + " " + post.user.surname %></p>
                        <% else %>
				<p>anonymous</p>
		        <% end %>
                        <strong><%= post.created_at.strftime("%m/%d/%y %H:%M") %></strong>
		<% end %>
	</td>
	<% if post.user != nil %>
	  <% if post.user.id == current_user.id %>
	    <td><%= link_to(image_tag('edit.png', alt: 'Edit',
		                       title: 'Edit item', border: '0'),
				edit_post_path(post)) %></td>
	    <td><%= link_to image_tag('destroy.gif', alt: 'Destroy', title: 'Destroy', border: '0'), post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
	    <% if current_user.login == "admin" %>
	    <td><%= link_to image_tag('destroy.gif', alt: 'Destroy', title: 'Destroy', border: '0'), post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>

          <% end %>
      <% else %>
        <% if current_user.login == "admin" %>
	    <td><%= link_to image_tag('destroy.gif', alt: 'Destroy', title: 'Destroy', border: '0'), post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>
<div class="digg_pagination">
  <div>
    <%= page_entries_info @posts %>
  </div>
   <%= will_paginate @posts, container: false %>
</div>
<br>

<%= link_to 'Create Thread', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path(page: @current_page) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<h3>Post</h3>
  <div style="background-color: silver; width:800px;">
	  <h3>RE: <%= @post.title %></h3>
  </div>
  <div style="display: inline-block; padding:5px; margin:5px; border:1px silver solid; max-width: 20%;">
    <% if @post.anonymous %>
	    <p>Anonymous</p>
    <% else %>
	    <p><%= link_to @post.user.firstname + " " + @post.user.surname, @post.user %></p>
    <%= image_for(@post.user, :medium) %>
	  <p>Date Joined: <%= @post.user.created_at.strftime("%m/%d/%y") %></p>
	  <p>Threads Created: <%= @post.user.posts.count %></p>
    <% end %>
  </div>
  <div style="display: inline-block; padding:5px; margin:5px; border:1px silver solid; width: 50%; vertical-align: top;">
	  <p><%= @post.created_at.strftime("%m/%d/%y %H:%M") %></p>
	  <p><%=raw @post.body %></p>
	  <p><%= link_to 'Reply To Thread', new_post_reply_path(@post.id) %> |
<% if @post.user != nil %>
  <% if current_user.id == @post.user.id %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
  <% end %>
<% end %>
<%= link_to 'Back', posts_path %></p>

  </div>
  <% readPost(@post, current_user.id) %>

<br>
<br>
<h3>Replies</h3>
<% @post.replies.each do |reply| %>
	<% if(reply.reply_id.nil?) %>
<div style="background-color: silver; width:800px;">
	  <h3>RE: <%= reply.title %></h3>
  </div>
  <div style="display: inline-block; padding:5px; margin:5px; border:1px silver solid; max-width: 20%;">
    <% if reply.anonymous %>
	    <p>Anonymous</p>
    <% else %>
	    <p><%= link_to reply.user.firstname + " " + reply.user.surname , reply.user%></p>
    <%= image_for(reply.user, :medium) %>
	  <p>Date Joined: <%= reply.user.created_at.strftime("%m/%d/%y") %></p>
	  <p>Threads Created: <%= reply.user.posts.count %></p>
    <% end %>
  </div>
  <div style="display: inline-block; padding:5px; margin:5px; border:1px silver solid; width: 50%; vertical-align: top;">
	  <p><%= reply.created_at.strftime("%m/%d/%y %H:%M") %></p>
	  <p><%=raw reply.body %></p>
	  <p><%= link_to 'Reply To Reply', new_post_reply_path(reply.post_id, reply: reply.id) %></p>
  </div>

  <div class="replies">
    <% subReplies = getReplies(reply) %>
    <% clearVars %>
    <% subReplies.each do |subReply| %>
      <% subPost = subReply[0] %>
      <% indent = subReply[1] %>
<div style="background-color: silver; width:800px; margin-left: <%= " #{indent * 50}px" %>">
	  <h3>RE: <%= subPost.title %></h3>
  </div>
  <div style="display: inline-block; padding:5px; margin:5px; border:1px silver solid; max-width: 20%; margin-left: <%= " #{indent * 50}px" %>">
    <% if subPost.anonymous %>
	    <p>Anonymous</p>
    <% else %>
	    <p><%= link_to subPost.user.firstname + " " + subPost.user.surname, subPost.user %></p>
    <%= image_for(subPost.user, :medium) %>
	  <p>Date Joined: <%= subPost.user.created_at.strftime("%m/%d/%y") %></p>
	  <p>Threads Created: <%= subPost.user.posts.count %></p>
    <% end %>
  </div>
  <div style="display: inline-block; padding:5px; margin:5px; border:1px silver solid; width: 50%; vertical-align: top;">
	  <p><%= subPost.created_at.strftime("%m/%d/%y %H:%M") %></p>
	  <p><%=raw subPost.body %></p>
	  <p><%= link_to 'Reply To Reply', new_post_reply_path(subPost.post_id, reply: subPost.id) %></p>

  </div>

    <% end %>
  </div> 
  <% end %>
<% end %>